# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# change to baidu
google-ID: '52fa527966646804deb0f196af9cc93e'

menu:
- {name: '首页', path: '', url: 'index.html'}
- {name: '关于', path: 'menu', url: 'about.html'}
- {name: '存档', path: 'menu', url: 'writing.html'}
- {name: '联系', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github', link: 'https://www.github.com/xionglaoliu'}
- {icon: 'weibo', link: 'https://weibo.com/u/3939426052'}
- {icon: 'Email', link: 'mailto:laoliu@xlaoliu.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site textindex
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: '立即分享!'

related_posts: '您可能还喜欢：'

post_date_prefix: '发表在'
